path:
  ckpt_path: "./output/ckpt/MovieAnimation"
  log_path: "./output/log/MovieAnimation"
  result_path: "./output/result/MovieAnimation"
optimizer:
  # batch_size: 16
  # batch_size 越大越快 精度降低
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  #total_step: 2000000
  log_step: 2500
  synth_step: 5000
  val_step: 2500
  # log_step: 5
  # synth_step: 5
  # val_step: 5
  save_step: 50000
